server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false # false来表明自己是一个eureka server.
    fetchRegistry: false # 表示是否从Eureka Server获取注册信息，默认为true。
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/